### ISSUE TITLE
Provide event hooks into the FBT API.

### ISSUE THREAD

**Issue by fruchtose** [facebookincubator/fbt#109]
## 🚀 Feature Proposal

Please provide an event emitter as part of FBT, so that developers can gain insights into how FBT operates under the hood.

## Motivation

FBT currently offers very little in the way of reporting what work goes on behind the scenes. For instance, how can a developer know if a provided string is being translated at runtime? Making `fbt` an event emitter with hooks for parts of the string substition process (language lookup, string lookup, etc.) would make the library easily introspectable. It would  allow teams to collect statistics and determine where translations are missing, among other potential features.

## Example

This example would show how Sentry could be triggered when a translation is missing.

```javascript
const fbt = require('fbt');
const Sentry = require('@sentry/browser');
fbt.on('missingTranslation', (language, hash) => {
  Sentry.withScope(scope => {
    scope.setExtras({ hash, language });
    Sentry.captureMessage('Missing translation');
  });
});
```

## Pitch

Potential users would be incentivized to choose FBT over competing solutions with better real-time data reporting. Executives want assurance that chosen software solutions are reliable. Without being able to inspect FBT as it works in real-time, developers would have to spend time writing more code and tooling to ensure that their translation system works as expected.

**Comment by jrwats** [comment]
**Missing translations**
@fruchtose, missing translations would be most appropriate at build-time when building translations (the work done in the [translate script](https://github.com/facebookincubator/fbt/blob/master/packages/babel-plugin-fbt/bin/translate.js)).  For the runtime, we *have* added [a few hooks](https://github.com/facebookincubator/fbt/blob/master/runtime/shared/FbtHooks.js#L18-L22) as of `0.11.0`, including the ability to override the result returned from the `fbt._(...)` runtime call https://github.com/facebookincubator/fbt/commit/5ba67907beb143d689d20997a595d92bb5702765

**A note on implementation**
We explicitly stayed away from an actual eventing mechanism and instead went with explicit callbacks due to the heavyweight nature of eventing machinery.  Given that `fbt` is going to show up almost anywhere we have text, we want to try and ensure it stays performant and brings in as few modules as possible.

**Real time data reporting / string lookup**
I'd encourage checking out `FbtHooks.logImpression`, it's probably what you want to take advantage of.

**Language lookup**
I'd question whether this should be done in FBT.  I'm not opposed to necessarily adding another hook for this, but it's expected that the application layer is going to be calling into FBT to switch languages/locales - not the other way around, so I'd question the value there.  Let me know your thoughts.

If you have any other hooks you'd like to see, or internals into which you'd like more introspection, please let us know.  I'm going to close this for now, but feel free to reopen.
